on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Determine git SHA short
      id: determine-sha-short
      run: 'echo "::set-output name=git-sha-short::${GITHUB_SHA::7}"'

    - name: Build and push
      id: docker_build
      env:
        DOCKER_BASE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/<<.Slug>>
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.DOCKER_BASE_TAG }}:${{ steps.determine-sha-short.outputs.git-sha-short }},${{ env.DOCKER_BASE_TAG }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - run: sed 's/${VERSION}/${{ steps.determine-sha-short.outputs.git-sha-short }}/g' k8s.yaml > _k8s.yaml

    - name: deploy to cluster
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f _k8s.yaml
