apiVersion: apps/v1
kind: Deployment
metadata:
  name: deasy-example
  labels:
    app: deasy-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deasy-example
  template:
    metadata:
      labels:
        app: deasy-example
    spec:
      containers:
      - name: deasy-example
        image: jeanpinzon/deasy-example:${VERSION}
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: deasy-service-example
spec:
  selector:
    app: deasy-example
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000