apiVersion: apps/v1
kind: Deployment
metadata:
  name: <<.Slug>>-deployment
  labels:
    app: <<.Slug>>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <<.Slug>>
  template:
    metadata:
      labels:
        app: <<.Slug>>
    spec:
      containers:
      - name: <<.Slug>>
        image: ${DOCKERHUB_USERNAME}/<<.Slug>>:${VERSION}
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: <<.Slug>>-service
spec:
  selector:
    app: <<.Slug>>
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000